### ISSUE TITLE
PHP Warning:  mkdir(): Not a directory in ..\vendor\illuminate\filesystem\Filesystem.php on line 466

### ISSUE THREAD

**Issue by patuan03** [stelgenhof/opensubtitles#2]
I have this issue when I run your code, I could be the wrong $path. Could you please help me to address this issue.
Thanks

**Comment by stelgenhof** [comment]
Hi,

Not sure what the issue is. Are you using the latest version of this app? Also, have updated the composer dependencies? 
Just tried it myself with the latest code, and I don't get such error message.

Cheers! Sacha

**Comment by stelgenhof** [comment]
Closing this issue. Assuming the issue no longer present. In case you still experience this error, please log a new issue.
Thanks!
