### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by BaiMaoLi** [stelgenhof/opensubtitles#3]
This guy, it is not working at all.

**Comment by stelgenhof** [comment]
@BaiMaoLi Sorry, could you explain more what exactly is not working? Can you share any error messages output you are seeing? Without these details it is a bit hard to understand your issue.

Thanks! Sacha

**Comment by BaiMaoLi** [comment]
Thanks for your replying.
[image: image.png]
I want to download subtitle from IMDB ID.
by the way, I can't understand your code.
what $argv[1] should be here?

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by BaiMaoLi** [comment]
https://github.com/kesar/PhpOpenSubtitles/blob/master/console.php
this is ur repository.

**Comment by BaiMaoLi** [comment]
Will you help me?

**Comment by stelgenhof** [comment]
Sorry, but https://github.com/kesar/PhpOpenSubtitles/blob/master/console.php is not my repository. I think you have logged the issue here by mistake.

**Comment by stelgenhof** [comment]
Please log the issue at the correct repository: https://github.com/kesar/PhpOpenSubtitles
